import { Inter, Ubuntu } from "next/font/google";
import "./globals.css";

import { CartProvider } from "@/context/CartContext";
import { GlobalProvider } from "./GlobalProvider";

import Script from "next/script";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Store | Navkar Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/next.svg" />
        <link rel="icon" type="image/png" sizes="16x16" href="/next.svg" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="mask-icon" href="/next.svg" color="#5bbad5" />
        <link rel="shortcut icon" href="/next.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover"
        />
      </head>

      <body className={ubuntu.className}>
        <Toaster />
        <GlobalProvider>
          <Header />
          <div className="w-full h-[2px] bg-black/10 rounded-full mb-6" />

          {children}

          <div className="w-full h-[2px] bg-black/10 rounded-full mt-6" />
          <Footer />
        </GlobalProvider>
      </body>
      <Script src="https://checkout.razorpay.com/v1/checkout.js" />
    </html>
  );
}
